### ISSUE TITLE
Page Size is not properly read when using components that uses the new Data Provider

### ISSUE THREAD

**Issue by samuelcardoso** [CruxFramework/crux-smart-faces#687]
Those components cannot read the page size properly:

org.cruxframework.crux.smartfaces.client.list.AbstractComboBox
org.cruxframework.crux.smartfaces.client.list.WidgetList

For instance, those components had a pageSize property inside them but that variable was not being updated according to the dataprovider. The correct way to threat this is by pointing that variable to the dataprovider that already has a variable to handle the page size.

**Comment by thiagobustamante** [comment]
This is a crux core issue. Please report it on crux repository
