### ISSUE TITLE
Change Carroussel component to allow user programmatically hide the controls buttons like back and next.

### ISSUE THREAD

**Issue by alexandretriggolabs** [CruxFramework/crux-smart-faces#851]
Change Carroussel component to allow user programmatically hide the controls buttons like back and next.

**Comment by thiagobustamante** [comment]
Carousel does not provide any navigation button. Probably, your are looking for each in the wrong place. SwapPager is a pager that can be used with Carousel widget and it provides navigations buttons. You can use the property navigationButtonsVisible to inform if the buttons must appears.
